// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDAoUTezaR70k0Fy0VfW2u-VECqbBl7MI',
    appId: '1:584408892560:android:72c3df301e5e7f1d71c415',
    messagingSenderId: '584408892560',
    projectId: 'chatapp-bc01e',
    storageBucket: 'chatapp-bc01e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYFc5Xbuot7xPODStwWr6YgFGgkGlpXYw',
    appId: '1:584408892560:ios:ad16d02aa038d50871c415',
    messagingSenderId: '584408892560',
    projectId: 'chatapp-bc01e',
    storageBucket: 'chatapp-bc01e.appspot.com',
    androidClientId: '584408892560-7lq5hn17ndedii5qtjkffpspbakfi069.apps.googleusercontent.com',
    iosClientId: '584408892560-u961mr2qh1mk3r2e90kr7unqk6hgk2tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
